from __future__ import annotations

"""
Pipeline Module 1 → 2 → 3 → 4 → 5

1. Module 1 (fecther/fetcher.py)
   - pulls the image via skopeo into an OCI image-layout
   - creates a docker-archive tar
   - performs umoci unpack (rootfs + config.json)

2. Module 2 (scanner/scanner.py)
   - runs Trivy and Grype on the docker-archive produced by Module 1
   - generates reports for Trivy, Grype, and Merged
   - compares CVE sets, field discrepancies, improvements, etc.
   - produces a vulnerability summary JSON

3. Module 3 (checker/checker.py)
   - reads the OCI layout produced by Module 1
   - selects the manifest for the requested platform
   - performs configuration checks + Dive analysis on the tar
   - produces JSON + Markdown reports with config issues and dive_summary

4. Module 4 (secret/secret.py)
   - scans the unpacked rootfs for secrets
   - uses custom regex rules + entropy analysis + TruffleHog + Gitleaks
   - deduplicates findings
   - produces JSON + Markdown reports with severity/type statistics

5. Module 5 (report/report.py)
   - reads the JSON outputs from Modules 2, 3, and 4
   - normalizes vulnerabilities, configuration issues, and secrets data
   - enriches CVEs with:
       * Exploit-DB (auto-updated CSV)
       * CISA KEV (Known Exploited Vulnerabilities catalog)
   - computes aggregated statistics (severity distribution, scanner coverage, top critical packages)
   - generates:
       * interactive HTML report (filters, SVG charts, dynamic top-N ranking)
       * static PDF report (via wkhtmltopdf)
       * consolidated report_summary.json
   - is resilient: does not fail if one of the input JSON files is missing
"""

import os
from pathlib import Path
import sys

from fetcher import fetcher     # Module 1
from scanner import scanner     # Module 2
from checker import checker     # Module 3
from secret import secret       # Module 4
from report import report       # Module 5

def run_pipeline(image_name: str, platform: str | None = None) -> None:
    """
    Runs the complete pipeline: Module 1 → 2 → 3 → 4 → 5
    """

    # ------------------------------------------------------------------
    # Module 1 – Image Fetcher (fetcher)                                     
    # ------------------------------------------------------------------

    print(f"[Pipeline] [1/5] Fetching image '{image_name}' "
          f"with platform={platform or 'multi-arch heuristic'}")

    fetched = fetcher.fetch_with_skopeo(
        image=image_name,
        out_root=fetcher.OUT_ROOT,
        platform=platform,
    )

    safe_name        = fetched["safe_name"]
    tar_path         = Path(fetched["tar_path"])
    unpacked_dir     = Path(fetched["unpacked_dir"])
    oci_dir          = Path(fetched["oci_dir"])
    unpacked_platform = fetched.get("unpacked_platform")

    print(f"[Pipeline] Docker archive: {tar_path}")
    print(f"[Pipeline] Unpacked rootfs bundle: {unpacked_dir}")
    print(f"[Pipeline] Unpacked platform: {unpacked_platform}")

    # This will be the platform to be passed to modules 2 and 3:
    platform_for_downstream = platform or unpacked_platform

    # ------------------------------------------------------------------
    # Module 2 – Vulnerability Scanner (scanner)
    # ------------------------------------------------------------------
    
    print(f"[Pipeline] [2/5] Vulnerability scan (Trivy + Grype) on the tar...")

    trivy_output_dir  = scanner.create_output_dir(safe_name, "Trivy_SKOPEO")
    grype_output_dir  = scanner.create_output_dir(safe_name, "Grype_SKOPEO")
    merged_output_dir = scanner.create_output_dir(safe_name, "Merged_SKOPEO")

    df_trivy = df_grype = df_merged = None

    # Directory where to save the expected_fields_*.json (if it doesn't exist)
    os.makedirs("scanner", exist_ok=True)

    trivy_json = os.path.join(trivy_output_dir, f"{safe_name}_trivy.json")
    grype_json = os.path.join(grype_output_dir, f"{safe_name}_grype.json")

    # --- Trivy: scan of the docker-archive produced by Module 1 ---
    trivy_args = [
        "trivy", "image",
        "--input", str(tar_path),     # use the tar generated by fetcher
        "--format", "json",
        "--output", trivy_json,
    ]
    trivy_data = scanner.run_scan(
        "trivy",
        image_name,
        trivy_args,
        "scanner/expected_fields_trivy.json",
    )

    if trivy_data:
        df_trivy = scanner.prepare_dataframe(trivy_data, "trivy")
        if df_trivy is not None:
            scanner.save_markdown_report(
                df_trivy, image_name, safe_name, trivy_output_dir, "trivy"
            )
            scanner.save_csv_report(df_trivy, safe_name, trivy_output_dir, "trivy")
            scanner.report_cve_distribution(
                trivy_data,
                trivy_output_dir,
                image_name,
                safe_name,
                scanner.get_missing_fields_by_cve,
                "trivy",
            )
        else:
            print("[Trivy] No vulnerabilities to export: Empty DataFrame.")
    else:
        print("[Trivy] No JSON output (scan failed or tool not present). "
              "Skipping export and reporting.")

    # --- Grype: scan of the docker-archive produced by Module 1 ---
    grype_args = [
        "grype", f"docker-archive:{tar_path}",
        "--output", "json",
        "--file", grype_json,
    ]
    grype_data = scanner.run_scan(
        "grype",
        image_name,
        grype_args,
        "scanner/expected_fields_grype.json",
    )

    if grype_data:
        df_grype = scanner.prepare_dataframe(grype_data, "grype")
        if df_grype is not None:
            scanner.save_markdown_report(
                df_grype, image_name, safe_name, grype_output_dir, "grype"
            )
            scanner.save_csv_report(df_grype, safe_name, grype_output_dir, "grype")
            scanner.report_cve_distribution(
                grype_data,
                grype_output_dir,
                image_name,
                safe_name,
                scanner.get_missing_fields_by_cve,
                "grype",
            )
        else:
            print("[Grype] No vulnerabilities to export: Empty DataFrame.")
    else:
        print("[Grype] No JSON output (scan failed or tool not present). "
              "Skipping export and reporting.")

    # --- Merge Trivy + Grype (if both available) ---
    if trivy_data and grype_data:
        print(f"[Merged] Performing merge and generating merged reports for: {image_name}")
        merged_data = scanner.merge_trivy_grype(trivy_data, grype_data)
        if merged_data:
            df_merged = scanner.prepare_dataframe(merged_data, "merged")
            if df_merged is not None:
                scanner.save_markdown_report(
                    df_merged, image_name, safe_name, merged_output_dir, "merged"
                )
                scanner.save_csv_report(df_merged, safe_name, merged_output_dir, "merged")
                # HERE is added the summary JSON for Module 5
                scanner.write_vuln_summary_json(
                    df_merged,
                    image_name=image_name,
                    safe_name=safe_name,
                    output_dir=merged_output_dir,
                    primary_source="merged",
                    platform=platform_for_downstream,
                )
            else:
                print("[Merged] No vulnerabilities to export: Empty DataFrame.")
        else:
            print("[Merged] Merge produced no records (no overlap or merge error).")

        scanner.report_extra_occurrences(
            trivy_data, grype_data, "Grype", safe_name, merged_output_dir
        )
        scanner.compare_cve_sets(
            trivy_data, grype_data, image_name, safe_name, merged_output_dir
        )
    else:
        print("[Merged] Merge skipped: need both Trivy and Grype reports.")

    if df_trivy is not None and df_grype is not None:
        scanner.report_discrepancies(
            df_trivy, df_grype, merged_output_dir, image_name, safe_name
        )

    if df_trivy is not None and df_merged is not None:
        scanner.report_improvements(
            orig_df=df_trivy,
            merged_df=df_merged,
            fields=["FixedVersion", "CVSS"],
            tool_name="trivy",
            image_name=image_name,
            merged_dir=merged_output_dir,
            safe_name=safe_name,
        )

    if df_grype is not None and df_merged is not None:
        scanner.report_improvements(
            orig_df=df_grype,
            merged_df=df_merged,
            fields=["FixedVersion", "CVSS"],
            tool_name="grype",
            image_name=image_name,
            merged_dir=merged_output_dir,
            safe_name=safe_name,
        )
    
    # If there's no valid df_merged but Trivy produced something,
    # we use Trivy as the source for the Module 5 synthesis JSON.
    if df_merged is None and df_trivy is not None:
        scanner.write_vuln_summary_json(
            df_trivy,
            image_name=image_name,
            safe_name=safe_name,
            output_dir=trivy_output_dir,
            primary_source="trivy",
            platform=platform_for_downstream,
        )


    # ------------------------------------------------------------------
    # Module 3 – Configuration Checker (check)
    # ------------------------------------------------------------------
    
    print(f"[Pipeline] [3/5] Configuration checker (newcheck) on the OCI layout...")

    # Use the same platform you chose from Module 1, if available
    checker_args = ["--oci-dir", str(oci_dir)]
    if platform_for_downstream:
        checker_args += ["--platform", platform_for_downstream]

    saved_argv = sys.argv[:]
    try:
        sys.argv = ["newcheck.py"] + checker_args
        checker.main()
    finally:
        sys.argv = saved_argv

    # ------------------------------------------------------------------
    # Module 4 – Secret Detector (secret)
    # ------------------------------------------------------------------
    
    print(f"[Pipeline] [4/5] Secret Detector running ...")

    # We already have unpacked_dir from Module 1 (fetched["unpacked_dir"])
    if not unpacked_dir.is_dir():
        raise SystemExit(
            f"[ERRORE] Directory 'unpacked' non trovata in: {unpacked_dir}"
        )

    # Run Module 4 passing only --unpacked-dir
    secret.main([
        "--unpacked-dir", str(unpacked_dir)
    ])

    print("[Pipeline] Module 4 completed. Report in outputs/secrets/.")
    
    # ------------------------------------------------------------------
    # Module 5 – Report Generator (Jinja2  + PDF)
    # ------------------------------------------------------------------
    print("[Pipeline] [5/5] Report Generator running.")

    # JSON vulnerability (summary from Module 2)
    vuln_summary_path = Path(merged_output_dir) / f"{safe_name}_vulns_summary.json"
    if not vuln_summary_path.is_file():
        # fallback: summary generated by Trivy, if the merge does not exist
        vuln_summary_path = Path(trivy_output_dir) / f"{safe_name}_vulns_summary.json"

    # JSON configuration checker (Module 3)
    config_json_path = Path("outputs/checked") / safe_name / "config_issues.json"

    # JSON secrets (Module 4)
    secrets_json_path = Path("outputs/secrets") / safe_name / f"{safe_name}_secrets.json"

    report.run_module5(
    vulns_json=vuln_summary_path,
    config_json=config_json_path,
    secrets_json=secrets_json_path,
    )

    print("[Pipeline] DONE (Module 1 - 2 - 3 - 4 - 5 completed).")




def main() -> None:
    import argparse

    ap = argparse.ArgumentParser(
        description="Pipeline Module 1 (fetcher) → 2 (scanner) → 3 (checker) → 4 (secret)"
    )
    ap.add_argument(
        "--image",
        required=True,
        help="Image name (es. nginx:latest)",
    )
    ap.add_argument(
        "--platform",
        help="Platform os/arch (es. linux/amd64). "
             "If omitted: Module 1 uses multi-arch heuristics; "
             "Modules 2 and 3 use the platform chosen by Module 1.",
    )

    args = ap.parse_args()
    run_pipeline(args.image, args.platform)


if __name__ == "__main__":
    main()
